name: aero_cache
description: "A high-performance HTTP caching library for Dart/Flutter with zstd compression, ETag/Last-Modified revalidation, and full Cache-Control directive support for mobile applications."
version: 1.0.1
homepage: https://github.com/nikaera/aero_cache
repository: https://github.com/nikaera/aero_cache
documentation: https://nikaera.com/aero_cache
issue_tracker: https://github.com/nikaera/aero_cache/issues

funding:
  - https://github.com/sponsors/nikaera

# screenshots:
#   - description: 'High-performance HTTP caching with compression'
#     path: screenshots/example.png

platforms:
  android:
  ios:

topics:
  - caching
  - compression
  - media
  - http
  - performance

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  zstandard: ^1.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  path_provider_platform_interface: ^2.1.2
  test: ^1.25.8
  very_good_analysis: ^9.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
