name: aero_cache
description: "A high-performance caching library for Dart/Flutter with zstd compression and ETag-based cache revalidation."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1

dependencies:
  crypto: ^3.0.0
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  zstandard: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  http: ^1.0.0
  path_provider_platform_interface: ^2.1.2
  test: ^1.24.0
  very_good_analysis: ^9.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
