name: Project CI

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  project-ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "21"
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.6"
          channel: "stable"
          cache: true
      - name: Install Flutter library
        run: flutter pub get
      - name: Set up the project and run the test
        run: flutter test
      - name: Linter
        run: dart fix --dry-run
      - name: Analyze
        run: dart analyze
